#!/bin/sh
# Prepares access to the host machine's kubectl/kubeconfig before starting
# the dashboard, so the container can list pods on the k8s cluster running
# on the Docker host (Docker Desktop, OrbStack, minikube, kind, etc.).
set -e

HOST_KUBECONFIG_SRC="${HOST_KUBECONFIG_SRC:-/host-kube/config}"
KUBECONFIG_DEST="${HOME}/.kube/config"

if [ -f "$HOST_KUBECONFIG_SRC" ]; then
  mkdir -p "${HOME}/.kube"
  cp "$HOST_KUBECONFIG_SRC" "$KUBECONFIG_DEST"

  # Kubeconfigs generated by local clusters (Docker Desktop, OrbStack, kind,
  # minikube) usually point the API server at 127.0.0.1/localhost, which
  # inside the container refers to the container itself, not the host.
  # Rewrite it to a hostname that resolves back to the host. Prefer
  # k8s.orb.local (OrbStack's own TLS cert includes this SAN) and fall back
  # to host.docker.internal (Docker Desktop / generic, requires
  # extra_hosts: host-gateway on Linux).
  if getent hosts k8s.orb.local >/dev/null 2>&1; then
    HOST_ALIAS="k8s.orb.local"
  else
    HOST_ALIAS="host.docker.internal"
  fi

  # Only rewrite cluster server URLs (lines containing "server:").
  sed -i \
    -e "/server:/ s#https://127\.0\.0\.1#https://${HOST_ALIAS}#g" \
    -e "/server:/ s#https://localhost#https://${HOST_ALIAS}#g" \
    "$KUBECONFIG_DEST"

  export KUBECONFIG="$KUBECONFIG_DEST"
  echo "using kubeconfig at $KUBECONFIG_DEST (server rewritten to ${HOST_ALIAS} where applicable)"
else
  echo "warning: no kubeconfig found at $HOST_KUBECONFIG_SRC; kubectl calls will fail" >&2
fi

exec /app/openab-dashboard "$@"
